live_config_reload = true

import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
LANG = "en_US.UTF-8"
LC_ALL = "en_US.UTF-8"
TERM = "xterm-256color"

[window]
decorations = "None"
dynamic_title = true
startup_mode = "Maximized"
title = "Alacritty"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font]
size = 13.0

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[cursor.style]
blinking = "Always"
shape = "Beam"

[cursor]
vi_mode_style = "Beam"

[shell]
args = ["--login"]
program = "/usr/bin/zsh"

[hints]
alphabet = "jfkdls;ahgurieowpq"
