#!/usr/bin/env zsh

# slides <file.md> --pdf
slides() {
    docker run \
        --rm \
        --init \
        -v "$(readlink -f "$1" | xargs dirname)":/home/marp/app \
        -e MARP_USER="$(id -u):$(id -g)" \
        -e LANG="$LANG" \
        marpteam/marp-cli \
        /home/marp/app/"$(basename "$1")" \
        "$@"
}